### ISSUE TITLE
google search problem

### ISSUE THREAD

**Issue by mrmezoo** [PHProxy/phproxy#23]
when i try to search using google i get this 
![image](https://user-images.githubusercontent.com/17590083/67622523-27613c00-f81b-11e9-90a0-fa8c04a3196c.png)
i have seen website using same script and google search working without problem
can i know the problem ?
and how i can solve it ?

**Comment by romuald-r** [comment]
Hello,

I checked on my side from a random OVH's public IP, and Google works without problems with the lastest release. The proxy you uses must simply have been banned from Google because of abuses (like bots/scrapping/etc).
Not a code problem I think, so

**Comment by PhoenixPeca** [comment]
Hi, It's me from Phoenix Peca facebook page that you messaged. I'm sorry for that inaccurate message, I have added restrictions on google because google usually blocks access to certain IP addresses.. I meant that you will be greeted by a captcha--which does not work properly with PHProxy. But if you want to go on anyway, please comment out these lines:

https://github.com/PHProxy/phproxy/blob/master/files/php/misc.php#L2-L4
